name: ThiemesPresents
main: nl.thieme.tp.Main
version: 1.0
api-version: 1.13
authors: [Thieme]
softdepend:
  - Essentials
description: Present wraps for everyone!
commands:
  givepresent:
    aliases: [givep]
    description: Give a present wrap