name: ThiemesPresents
main: nl.thieme.tp.Main
version: 1.0
authors: [Thieme]
description: Present wraps for everyone!
commands:
  givepresent:
    aliases: [givep]
    description: Give a present wrap