name: ThiemesPresents
main: nl.thieme.tp.Main
version: 1.0
api-version: 1.13
authors: [ThiemeH]
softdepend: [Essentials]
description: Present wraps for everyone!
commands:
  thiemespresents:
    description: Main command
    aliases: [present, presents]