# Presents can be signed (= custom text in lore)
can-sign: true


# Please use 1.13+ item names!
# Blocked Slot Item
blocked-slot-material: GRAY_STAINED_GLASS_PANE
# Material when waiting for item to be selected
pending-material: ORANGE_CONCRETE
# Material for click to confirm
confirm-material: LIME_CONCRETE


# Allow storage items (shulker boxes, chests) to be wrapped
allow-wrapping-storage-items: false

# Sounds
open-sound:
  sound: ENTITY_HORSE_SADDLE
  volume: 0.4
  pitch: 1.3

wrap-sound:
  sound: ENTITY_HORSE_SADDLE
  volume: 0.4
  pitch: 2.0



# Presents can get a different name in anvil
can-rename-in-anvil: false

sign-character-limit: 200

signing-timeout-seconds: 30

# Disables crafting of recipes in the following worlds
disabled-worlds:
  - disabled-world

# Coming soon:

# presents-can-be-placed-on-head: false

# How many storage items can be wrapped inside a wrapped storage item
# storage-item-wrapping-limit: 2