# Presents can be signed (= custom text in lore)
can-sign: true


# Blocked Slot Item
blocked-slot-material: GRAY_STAINED_GLASS_PANE
# Material when waiting for item to be selected
pending-material: ORANGE_CONCRETE
# Material for click to confirm
confirm-material: LIME_CONCRETE


# Allow storage items (shulker boxes, chests) to be wrapped
allow-wrapping-storage-items: false

# How many storage items can be wrapped inside a wrapped storage item
storage-item-wrapping-limit: 2

# Presents can get a different name in anvil
can-rename-in-anvil: false

sign-character-limit: 200

signing-timeout-seconds: 30
