name: ${project.name}
main: nl.thieme.tp.Main
version: ${project.version}
api-version: 1.13
authors: [ThiemeH]
softdepend: [Essentials]
description: ${project.description}
commands:
  thiemespresents:
    description: Main command
    aliases: [present, presents]